### ISSUE TITLE
Data | Credit Card Holder

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#353] opened 2017-05-04 22:43 UTC
Passenger TYKAL, patrick on flight KL0651 is displaying a credit card holder name that matches the last four of the Credit Card Number, but does not match the expiration or type. The logic here is incorrect.

**Comment by dje04001** [comment] 2017-05-04 22:45
![uploads/87e53160-a2f3-46d0-b005-062d787753e8/Capture.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F87e53160-a2f3-46d0-b005-062d787753e8%2FCapture.PNG)

**Comment by dje04001** [comment] 2017-05-12 15:24
Related examples--

In the DEV site, A query on Credit Card--Account Holder begins with mck returns a record for passenger, JERDE, Cale.
In the PNR details, the credit card holder doesn't match the query inputs.

Querying Credit Card--Number--Ends With--7530 returns a record forJERDE, Cale that does not contain this credit card number in the PNR

**Comment by svempati2006** [comment] 2017-05-22 16:14
Loaded the 40 files in Synthetic_PNR_Messages_20170419_20170421 folder but not able to reproduce since it does not contain the credit card number and card holder name with JERDE. This might be a bad credit card data with multiple references to multiple passengers issue,

**Comment by svempati2006** [comment] 2017-05-22 18:27
Credit card expiration date parsing is not correctly handled in the code.Modified the date format and fixed the issue and unit tested and checked in to BitBucket.

**Comment by dje04001** [comment] 2017-05-24 15:15
This issue was easily recreated by taking any PNR message, and changing all of the credit card numbers to the same value.

**Comment by dje04001** [comment] 2017-05-30 19:46
This is not working properly. Please refer to the test data in the regression testing set.
3_Credit Card Test.txt
All passengers where FOP = CC were given the info
FOP+CC:::MA:XXXXXXXX0338:0219'
The sponsor information in the PNR does not match what's displayed or what's in the database

**Closed** 2017-08-03 04:59 UTC
Labels: 4 - Done, bug
