### ISSUE TITLE
PROD Data | Origin / Destination Country

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#356] opened 2017-05-05 20:01 UTC
For a round-trip PNR itinerary where first and last airports are the same, we're displaying the Origin and Destination countries as the same value. This should be based on the longest dwell time.

**Comment by svempati2006** [comment] 2017-05-19 14:28
Trying to load 356.txt test data but looks like this is not the pnr data to reproduce the issue .Can we get test data for this?

**Comment by dje04001** [comment] 2017-05-19 14:37
just put a pnr file in the google drive

**Comment by svempati2006** [comment] 2017-05-22 15:32
Code completed ,unit tested and checked into Sanandreas (Bitbucket)

**Closed** 2017-06-14 21:51 UTC
Labels: 4 - Done
