### ISSUE TITLE
Query Builder | editable text window for recreating / editing complex rules

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#208] opened 2017-01-19 15:15 UTC

**Comment by dje04001** [comment] 2017-02-03 08:03
Mike can do a better job of explaining the requirements. Let's get together to discuss when you're ready.

**Comment by originalname51** [comment] 2019-05-10 16:06
This appears to have been finished; possible duplicate of #1071

**Comment by dje04001** [comment] 2019-05-10 16:26
We don't need this. This was for constructing your own drools if a user
knows what they're doing. It's not really necessary since it could be fed
to the database anyways.

**Closed** 2019-05-15 03:45 UTC
Labels: 3 - Review, New Feature
