### ISSUE TITLE
Health Check on GUI

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#1223] opened 2019-06-27 17:34 UTC

**Comment by tjwdev** [comment] 2019-06-27 20:34
Further clarification, at a minimum we need a method to tell if rules and loader are actively up and running. Minimally we need to have a simple red light/green light that the particular service is running from the front-end.

**Comment by originalname51** [comment] 2019-07-29 18:33
Duplicate of #1240

**Closed by originalname51** 2019-07-29 18:33 UTC
Labels: 0 - Backlog, duplicate
