### ISSUE TITLE
Flight_Pax table restructuring and renaming

### ISSUE THREAD

**Issue by tjwdev** [US-CBP/GTAS#663] opened 2017-09-14 16:22 UTC
Flight_Pax table is actually apis related flight_pax information. This should be renamed to something to indicate that it is that particular type of file representation. Rename to: apis_flight_pax.

debarkation, deb_country, embarkation, emb_country are all retrievable through the flight_id connection and most likely do not need to be stored in the table as well and should be removed.

**Comment by originalname51** [comment] 2020-04-06 21:29
ended up deprecating the table and partially removing it to enable backwards compatibility.

**Comment by originalname51** [comment] 2020-04-06 21:29
duplicate of #1758

**Closed by originalname51** 2020-04-06 21:29 UTC
Labels: 3 - Review, duplicate
