### ISSUE TITLE
APIS Tab | Remove Baggage destination

### ISSUE THREAD

**Issue by dje04001** [US-CBP/GTAS#657] opened 2017-09-10 15:33 UTC
This data element comes from PNR, and should be located on the PNR tab.

**Comment by svempati2006** [comment] 2017-09-12 13:48
The Bag class provides  source property which will let the UI developers to filter the things in PNR or APIS tab.Front end fix.Please assign it to UI developer.

**Comment by donleyac** [comment] 2017-09-28 15:21
From the frontend perspective the bag information is populated respective to the vo that was passed. For instance on the pnr tab, bags are displayed from PNRVO->BAGVO and for the apis tab it is APISMESSAGEVO->BAG. These are chunked by the backend by checking the source of the bag whether it is from apis or pnr. So from my perspective the only way that the frontend could display the wrong information is if pnr bag information is being misplaced on apis bag rows in the database. However, all my loaded files look fine. I would need pnr/apis data where this mismatch has occurred.

**Comment by svempati2006** [comment] 2017-10-10 14:20
Not reproducible.This issue may be due to bad data at the time of adding source attribute.Review it and close this.

**Comment by dje04001** [comment] 2017-11-01 18:42
Sorry for the long delay on the comment here, my description here wasn't very good. My original concern is that the APIS tab is displaying Destination in the Bag table, when this information doesn't come from the APIS message. It might be somewhat misleading to the user include this on the APIS tab. This isn't a top priority, but maybe we should remove that column from the table. Open to suggestions--

**Comment by svempati2006** [comment] 2017-11-06 14:40
PNR data provides the destination airport for the bag.So its better to store the available information and we can remove the destination column from the APIS bag details section in the UI.

**Comment by svempati2006** [comment] 2018-05-22 18:52
Code completed unit tested and checked into Dev branch.Pl review.

**Closed** 2018-08-13 19:41 UTC
Labels: 4 - Done, Sprint 4 (5/28 - 6/8), bug
